-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_ShopSetting" (
    "id" TEXT NOT NULL PRIMARY KEY DEFAULT 'singleton',
    "shopName" TEXT NOT NULL DEFAULT '자비샵',
    "verifyRoleId" TEXT,
    "bankName" TEXT NOT NULL DEFAULT '',
    "bankAccountNumber" TEXT NOT NULL DEFAULT '',
    "bankAccountHolder" TEXT NOT NULL DEFAULT '',
    "bankWebhookSecret" TEXT,
    "refundAllowedAfterDownload" BOOLEAN NOT NULL DEFAULT false,
    "noticeMessage" TEXT,
    "discordPurchaseLogChannelId" TEXT,
    "discordMemberCountChannelId" TEXT,
    "discordBuyerCountChannelId" TEXT,
    "discordAutoDeleteChannelId" TEXT,
    "discordRoleTier150k" TEXT,
    "discordRoleTier100k" TEXT,
    "discordRoleTier50k" TEXT,
    "discordRoleTier10k" TEXT,
    "discordRoleBuyer" TEXT,
    "partnerCategoryId" TEXT,
    "partnerRoleId" TEXT,
    "partnerDailyMessage" TEXT,
    "partnerLastBroadcast" DATETIME,
    "sellerCategoryId" TEXT,
    "sellerTicketCategoryId" TEXT,
    "sellerRoleId" TEXT,
    "sellerMonthlyPrice" INTEGER NOT NULL DEFAULT 1000,
    "sellerFreeTrialDays" INTEGER NOT NULL DEFAULT 30,
    "announcementChannelId" TEXT,
    "dailyStatsLastPosted" DATETIME,
    "publicStatsChannelId" TEXT,
    "publicStatsMessageId" TEXT,
    "adminDutyChannelId" TEXT,
    "adminDutyMessageId" TEXT,
    "adminDutyControlChannelId" TEXT,
    "adminDutyControlMessageId" TEXT,
    "purchaseCouponDropEnabled" BOOLEAN NOT NULL DEFAULT false,
    "discountModeEnabled" BOOLEAN NOT NULL DEFAULT false,
    "checkInEventEnabled" BOOLEAN NOT NULL DEFAULT false,
    "flashSaleEventEnabled" BOOLEAN NOT NULL DEFAULT false,
    "referralEventEnabled" BOOLEAN NOT NULL DEFAULT false,
    "gachaEventEnabled" BOOLEAN NOT NULL DEFAULT false,
    "gachaCostPoints" INTEGER NOT NULL DEFAULT 100,
    "buyOneGetOneEventEnabled" BOOLEAN NOT NULL DEFAULT false,
    "promoReportLastSentAt" DATETIME,
    "promoStaffRoleId" TEXT,
    "antiSpamEnabled" BOOLEAN NOT NULL DEFAULT false,
    "antiSpamLogChannelId" TEXT,
    "antiSpamWhitelistRoleId" TEXT,
    "antiSpamFloodCount" INTEGER NOT NULL DEFAULT 6,
    "antiSpamFloodWindowSec" INTEGER NOT NULL DEFAULT 5,
    "antiSpamMentionLimit" INTEGER NOT NULL DEFAULT 5,
    "antiSpamEmergencyThreshold" INTEGER NOT NULL DEFAULT 10,
    "antiSpamEmergencyWindowSec" INTEGER NOT NULL DEFAULT 60,
    "antiSpamEmergencyDurationMin" INTEGER NOT NULL DEFAULT 10,
    "antiSpamBlockImages" BOOLEAN NOT NULL DEFAULT false,
    "antiSpamBlockVideos" BOOLEAN NOT NULL DEFAULT false,
    "antiSpamAltAccountMinAgeDays" INTEGER NOT NULL DEFAULT 0,
    "antiSpamSimilarNameCheck" BOOLEAN NOT NULL DEFAULT false
);
INSERT INTO "new_ShopSetting" ("adminDutyChannelId", "adminDutyControlChannelId", "adminDutyControlMessageId", "adminDutyMessageId", "announcementChannelId", "antiSpamEmergencyDurationMin", "antiSpamEmergencyThreshold", "antiSpamEmergencyWindowSec", "antiSpamEnabled", "antiSpamFloodCount", "antiSpamFloodWindowSec", "antiSpamLogChannelId", "antiSpamMentionLimit", "antiSpamWhitelistRoleId", "bankAccountHolder", "bankAccountNumber", "bankName", "bankWebhookSecret", "buyOneGetOneEventEnabled", "checkInEventEnabled", "dailyStatsLastPosted", "discordAutoDeleteChannelId", "discordBuyerCountChannelId", "discordMemberCountChannelId", "discordPurchaseLogChannelId", "discordRoleBuyer", "discordRoleTier100k", "discordRoleTier10k", "discordRoleTier150k", "discordRoleTier50k", "discountModeEnabled", "flashSaleEventEnabled", "gachaCostPoints", "gachaEventEnabled", "id", "noticeMessage", "partnerCategoryId", "partnerDailyMessage", "partnerLastBroadcast", "partnerRoleId", "promoReportLastSentAt", "promoStaffRoleId", "publicStatsChannelId", "publicStatsMessageId", "purchaseCouponDropEnabled", "referralEventEnabled", "refundAllowedAfterDownload", "sellerCategoryId", "sellerFreeTrialDays", "sellerMonthlyPrice", "sellerRoleId", "sellerTicketCategoryId", "shopName", "verifyRoleId") SELECT "adminDutyChannelId", "adminDutyControlChannelId", "adminDutyControlMessageId", "adminDutyMessageId", "announcementChannelId", "antiSpamEmergencyDurationMin", "antiSpamEmergencyThreshold", "antiSpamEmergencyWindowSec", "antiSpamEnabled", "antiSpamFloodCount", "antiSpamFloodWindowSec", "antiSpamLogChannelId", "antiSpamMentionLimit", "antiSpamWhitelistRoleId", "bankAccountHolder", "bankAccountNumber", "bankName", "bankWebhookSecret", "buyOneGetOneEventEnabled", "checkInEventEnabled", "dailyStatsLastPosted", "discordAutoDeleteChannelId", "discordBuyerCountChannelId", "discordMemberCountChannelId", "discordPurchaseLogChannelId", "discordRoleBuyer", "discordRoleTier100k", "discordRoleTier10k", "discordRoleTier150k", "discordRoleTier50k", "discountModeEnabled", "flashSaleEventEnabled", "gachaCostPoints", "gachaEventEnabled", "id", "noticeMessage", "partnerCategoryId", "partnerDailyMessage", "partnerLastBroadcast", "partnerRoleId", "promoReportLastSentAt", "promoStaffRoleId", "publicStatsChannelId", "publicStatsMessageId", "purchaseCouponDropEnabled", "referralEventEnabled", "refundAllowedAfterDownload", "sellerCategoryId", "sellerFreeTrialDays", "sellerMonthlyPrice", "sellerRoleId", "sellerTicketCategoryId", "shopName", "verifyRoleId" FROM "ShopSetting";
DROP TABLE "ShopSetting";
ALTER TABLE "new_ShopSetting" RENAME TO "ShopSetting";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
